### ISSUE TITLE
code for using lcd and ambient light sensor module of the board

### ISSUE THREAD

**Issue by uditagarwal97** [visakhanc/Kinetis_KL46#1]
Hello sir,
Please share the code for using LCD module and ambient light sensor of  FRDM-KL46z board

**Comment by visakhanc** [comment]
Hi,
I have a driver for segment LCD of KL46Z [here](https://github.com/visakhanc/Kinetis_KL46/tree/master/remote_gps_uCOSIII/Sources)
Have a look at the driver and report any further issue
As for ambient light sensor, I have not yet started on that.
